config/routes.rb
Rails.application.routes.draw do
  resources :test_models
  post 'requests/receive_request'
  get 'requests/receive_request' => 'requests#receive_request'

  root 'test_models#index'

end

app/models/requests_worker.rb
class RequestsWorker 
  include Sneakers::Worker
  from_queue "requests"


  def work(raw_post)
    p raw_post
    WebsocketRails['requests'].trigger('new', raw_post)
    ack! # we need to let queue know that message was received
  end
end

app/models/test_model.rb
class TestModel < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < WebsocketRails::BaseController
  def receive_request
  	 p message
  	 send_message :request_received, message, :namespace => :requests
  end
end

app/controllers/test_models_controller.rb
class TestModelsController < ApplicationController
  before_action :set_test_model, only: [:show, :edit, :update, :destroy]

  # GET /test_models
  # GET /test_models.json
  def index
    @test_models = TestModel.all
  end

  # GET /test_models/1
  # GET /test_models/1.json
  def show
  end

  # GET /test_models/new
  def new
    @test_model = TestModel.new
  end

  # GET /test_models/1/edit
  def edit
  end

  # POST /test_models
  # POST /test_models.json
  def create
    @test_model = TestModel.new(test_model_params)

    respond_to do |format|
      if @test_model.save
        format.html { redirect_to @test_model, notice: 'Test model was successfully created.' }
        format.json { render :show, status: :created, location: @test_model }
      else
        format.html { render :new }
        format.json { render json: @test_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_models/1
  # PATCH/PUT /test_models/1.json
  def update
    respond_to do |format|
      if @test_model.update(test_model_params)
        format.html { redirect_to @test_model, notice: 'Test model was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_model }
      else
        format.html { render :edit }
        format.json { render json: @test_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_models/1
  # DELETE /test_models/1.json
  def destroy
    @test_model.destroy
    respond_to do |format|
      format.html { redirect_to test_models_url, notice: 'Test model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_model
      @test_model = TestModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_model_params
      params.require(:test_model).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/test_models_helper.rb
module TestModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atendimento</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/requests/receive_request.html.erb
<h1>Requests#receive_request</h1>
<p>Find me in app/views/requests/receive_request.html.erb</p>

app/views/test_models/_form.html.erb
<%= form_for(@test_model) do |f| %>
  <% if @test_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_model.errors.count, "error") %> prohibited this test_model from being saved:</h2>

      <ul>
      <% @test_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_models/edit.html.erb
<h1>Editing Test Model</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_model %> |
<%= link_to 'Back', test_models_path %>

app/views/test_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Solicitações Recebidas</h1>
<div id="requests" >
      
</div>

app/views/test_models/new.html.erb
<h1>New Test Model</h1>

<%= render 'form' %>

<%= link_to 'Back', test_models_path %>

app/views/test_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @test_model.name %>
</p>

<%= link_to 'Edit', edit_test_model_path(@test_model) %> |
<%= link_to 'Back', test_models_path %>